print('== Cadasto da escola ==')
nome = input('Digite o nome:')
print('Bem vindo(a) '+nome)
lazer = input('O que gosta de fazer?')
print(lazer)
cor = input('Qual sua cpr favorita?')
print('A cor favorita é '+cor)
time = input('Qual seu time de volei?')
print('Time do coração '+time)
filme = input('Qual seu filme preerido?')
print('Seu filme favorito é '+filme)
